// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mlagents_envs/communicator_objects/agent_info_action_pair.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct CommunicatorObjects_AgentInfoActionPairProto {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var agentInfo: CommunicatorObjects_AgentInfoProto {
    get {return _agentInfo ?? CommunicatorObjects_AgentInfoProto()}
    set {_agentInfo = newValue}
  }
  /// Returns true if `agentInfo` has been explicitly set.
  var hasAgentInfo: Bool {return self._agentInfo != nil}
  /// Clears the value of `agentInfo`. Subsequent reads from it will return its default value.
  mutating func clearAgentInfo() {self._agentInfo = nil}

  var actionInfo: CommunicatorObjects_AgentActionProto {
    get {return _actionInfo ?? CommunicatorObjects_AgentActionProto()}
    set {_actionInfo = newValue}
  }
  /// Returns true if `actionInfo` has been explicitly set.
  var hasActionInfo: Bool {return self._actionInfo != nil}
  /// Clears the value of `actionInfo`. Subsequent reads from it will return its default value.
  mutating func clearActionInfo() {self._actionInfo = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _agentInfo: CommunicatorObjects_AgentInfoProto? = nil
  fileprivate var _actionInfo: CommunicatorObjects_AgentActionProto? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "communicator_objects"

extension CommunicatorObjects_AgentInfoActionPairProto: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AgentInfoActionPairProto"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "agent_info"),
    2: .standard(proto: "action_info"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._agentInfo)
      case 2: try decoder.decodeSingularMessageField(value: &self._actionInfo)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._agentInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if let v = self._actionInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CommunicatorObjects_AgentInfoActionPairProto, rhs: CommunicatorObjects_AgentInfoActionPairProto) -> Bool {
    if lhs._agentInfo != rhs._agentInfo {return false}
    if lhs._actionInfo != rhs._actionInfo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
