// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mlagents_envs/communicator_objects/engine_configuration.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct CommunicatorObjects_EngineConfigurationProto {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var width: Int32 = 0

  var height: Int32 = 0

  var qualityLevel: Int32 = 0

  var timeScale: Float = 0

  var targetFrameRate: Int32 = 0

  var showMonitor: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "communicator_objects"

extension CommunicatorObjects_EngineConfigurationProto: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EngineConfigurationProto"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "width"),
    2: .same(proto: "height"),
    3: .standard(proto: "quality_level"),
    4: .standard(proto: "time_scale"),
    5: .standard(proto: "target_frame_rate"),
    6: .standard(proto: "show_monitor"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.width)
      case 2: try decoder.decodeSingularInt32Field(value: &self.height)
      case 3: try decoder.decodeSingularInt32Field(value: &self.qualityLevel)
      case 4: try decoder.decodeSingularFloatField(value: &self.timeScale)
      case 5: try decoder.decodeSingularInt32Field(value: &self.targetFrameRate)
      case 6: try decoder.decodeSingularBoolField(value: &self.showMonitor)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.width != 0 {
      try visitor.visitSingularInt32Field(value: self.width, fieldNumber: 1)
    }
    if self.height != 0 {
      try visitor.visitSingularInt32Field(value: self.height, fieldNumber: 2)
    }
    if self.qualityLevel != 0 {
      try visitor.visitSingularInt32Field(value: self.qualityLevel, fieldNumber: 3)
    }
    if self.timeScale != 0 {
      try visitor.visitSingularFloatField(value: self.timeScale, fieldNumber: 4)
    }
    if self.targetFrameRate != 0 {
      try visitor.visitSingularInt32Field(value: self.targetFrameRate, fieldNumber: 5)
    }
    if self.showMonitor != false {
      try visitor.visitSingularBoolField(value: self.showMonitor, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CommunicatorObjects_EngineConfigurationProto, rhs: CommunicatorObjects_EngineConfigurationProto) -> Bool {
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.qualityLevel != rhs.qualityLevel {return false}
    if lhs.timeScale != rhs.timeScale {return false}
    if lhs.targetFrameRate != rhs.targetFrameRate {return false}
    if lhs.showMonitor != rhs.showMonitor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
