//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: mlagents_envs/communicator_objects/unity_to_external.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate CommunicatorObjects_UnityToExternalProtoClient, then call methods of this protocol to make API calls.
internal protocol CommunicatorObjects_UnityToExternalProtoClientProtocol: GRPCClient {
  func exchange(
    _ request: CommunicatorObjects_UnityMessageProto,
    callOptions: CallOptions?
  ) -> UnaryCall<CommunicatorObjects_UnityMessageProto, CommunicatorObjects_UnityMessageProto>

}

extension CommunicatorObjects_UnityToExternalProtoClientProtocol {

  /// Sends the academy parameters
  ///
  /// - Parameters:
  ///   - request: Request to send to Exchange.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func exchange(
    _ request: CommunicatorObjects_UnityMessageProto,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<CommunicatorObjects_UnityMessageProto, CommunicatorObjects_UnityMessageProto> {
    return self.makeUnaryCall(
      path: "/communicator_objects.UnityToExternalProto/Exchange",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class CommunicatorObjects_UnityToExternalProtoClient: CommunicatorObjects_UnityToExternalProtoClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the communicator_objects.UnityToExternalProto service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol CommunicatorObjects_UnityToExternalProtoProvider: CallHandlerProvider {
  /// Sends the academy parameters
  func exchange(request: CommunicatorObjects_UnityMessageProto, context: StatusOnlyCallContext) -> EventLoopFuture<CommunicatorObjects_UnityMessageProto>
}

extension CommunicatorObjects_UnityToExternalProtoProvider {
  internal var serviceName: Substring { return "communicator_objects.UnityToExternalProto" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "Exchange":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.exchange(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

