// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mlagents_envs/communicator_objects/unity_input.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct CommunicatorObjects_UnityInputProto {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var rlInput: CommunicatorObjects_UnityRLInputProto {
    get {return _rlInput ?? CommunicatorObjects_UnityRLInputProto()}
    set {_rlInput = newValue}
  }
  /// Returns true if `rlInput` has been explicitly set.
  var hasRlInput: Bool {return self._rlInput != nil}
  /// Clears the value of `rlInput`. Subsequent reads from it will return its default value.
  mutating func clearRlInput() {self._rlInput = nil}

  var rlInitializationInput: CommunicatorObjects_UnityRLInitializationInputProto {
    get {return _rlInitializationInput ?? CommunicatorObjects_UnityRLInitializationInputProto()}
    set {_rlInitializationInput = newValue}
  }
  /// Returns true if `rlInitializationInput` has been explicitly set.
  var hasRlInitializationInput: Bool {return self._rlInitializationInput != nil}
  /// Clears the value of `rlInitializationInput`. Subsequent reads from it will return its default value.
  mutating func clearRlInitializationInput() {self._rlInitializationInput = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _rlInput: CommunicatorObjects_UnityRLInputProto? = nil
  fileprivate var _rlInitializationInput: CommunicatorObjects_UnityRLInitializationInputProto? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "communicator_objects"

extension CommunicatorObjects_UnityInputProto: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UnityInputProto"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "rl_input"),
    2: .standard(proto: "rl_initialization_input"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._rlInput)
      case 2: try decoder.decodeSingularMessageField(value: &self._rlInitializationInput)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._rlInput {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if let v = self._rlInitializationInput {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CommunicatorObjects_UnityInputProto, rhs: CommunicatorObjects_UnityInputProto) -> Bool {
    if lhs._rlInput != rhs._rlInput {return false}
    if lhs._rlInitializationInput != rhs._rlInitializationInput {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
